version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /ui
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /website
  schedule:
    interval: daily
