sudo: required

language: go

services:
  - docker

go:
  - 1.7

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master
    - travis-testing

script:
  - make test testrace
  - docker run -v $(pwd):/cwd didrocks/snapcraft sh -c 'cd /cwd && apt install -y software-properties-common && add-apt-repository ppa:gophers/archive && apt update && apt install -y golang-1.7-go && snapcraft'
