sudo: required
dist: trusty

language: go

services:
  - docker

go:
  - 1.8.3

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master
    - travis-testing

script:
  - make bootstrap
  - TEST="github.com/hashicorp/vault/helper/keysutil" make test testrace
