name: Acceptance Tests Docker Only

on: [push]

jobs:
  plugins-database:
    uses: ./.github/workflows/reusable-run-go-acceptance-test.yml
    strategy:
      matrix:
        name: [mongodb, mysql, postgresql]
    with:
      name: plugins-database-${{ matrix.name }}
      path: plugins/database/${{ matrix.name }}

  external:
    uses: ./.github/workflows/reusable-run-go-acceptance-test.yml
    strategy:
      matrix:
        name: [api, identity, token]
    with:
      name: external-${{ matrix.name }}
      path: vault/external_tests/${{ matrix.name }}
