---
name: build

on:
  pull_request:
    branches:
      - docs/**
      - backport/docs/**

jobs:
  # Trigger the build / success workflow as it is required by branch restrictions
  success:
    runs-on: ubuntu-latest
    steps:
      - run: echo "All build and integration workflows have succeeded!"
